#!/bin/bash

# install-- make symbolic links in the users home directory
# Mike Barker <mike@thebarkers.com>
# May 14th, 2013

# 2015.04.30 MRB
# * renamed from makelinks.sh to install.sh
# * force create the sympolic links

DIR="$(cd "$(dirname "$0")" && pwd)"
stow -d "${DIR}" -t "$HOME" -R home
